# Generated by Django 2.2.6 on 2020-01-26 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Admin_Name', models.CharField(max_length=10)),
                ('Admin_PW', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_OP_IP_Cus', models.CharField(max_length=50)),
                ('S_OP_IP_Che', models.DateField(default=datetime.date)),
                ('S_ME_CI_Nam', models.CharField(max_length=10)),
                ('S_ME_CI_Sex', models.BooleanField()),
                ('S_ME_CI_Bir', models.DateField()),
                ('S_OP_IP_Bal', models.FloatField()),
                ('S_OP_IP_Bal1', models.FloatField()),
                ('S_OP_IP_Axe', models.IntegerField()),
                ('S_OP_IP_Axe1', models.IntegerField()),
                ('S_OP_IP_Pos', models.FloatField()),
                ('S_OP_IP_Pos1', models.FloatField()),
                ('Eq_Degree', models.FloatField()),
                ('Eq_Degree1', models.FloatField()),
                ('Age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('S_OP_IP_Cus', models.CharField(max_length=50)),
                ('S_ME_CI_Nam', models.CharField(max_length=10)),
                ('S_ME_CI_Sex', models.BooleanField()),
                ('S_ME_CI_Bir', models.DateField()),
                ('S_ME_CI_PW', models.CharField(max_length=20)),
            ],
        ),
    ]
