# Generated by Django 2.2.6 on 2020-02-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_prediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('female', models.IntegerField()),
                ('male', models.IntegerField()),
                ('age0to12', models.IntegerField()),
                ('age12to18', models.IntegerField()),
                ('age18to24', models.IntegerField()),
                ('age24to', models.IntegerField()),
            ],
        ),
    ]
